[site1]
vm1-pfsense-s1    ansible_host=10.1.0.1
vm2-elastic-s1    ansible_host=10.1.0.20
vm3-netbox-s1     ansible_host=10.1.0.30

[site2]
vm1-pfsense-s2    ansible_host=10.2.0.1
vm2-bastion-s2    ansible_host=10.2.0.20
vm3-vault-s2      ansible_host=10.2.0.30

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_rsa
